Add ohmyzsh install and temp disable further steps

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -49,6 +49,13 @@ setup_gitconfig () {
   fi
 }
 
+install_ohmyzsh() {
+  if ! [ -d ~/.oh-my-zsh ]
+  then
+    # https://ohmyz.sh/#install
+    /bin/zsh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+  fi
+}
 
 link_file () {
   local src=$1 dst=$2
@@ -138,19 +145,20 @@ install_dotfiles () {
 }
 
 setup_gitconfig
-install_dotfiles
+install_ohmyzsh
+#install_dotfiles
 
 # If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot > /tmp/dotfiles-dot 2>&1
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
+#if [ "$(uname -s)" == "Darwin" ]
+#then
+#  info "installing dependencies"
+#  if source bin/dot > /tmp/dotfiles-dot 2>&1
+#  then
+#    success "dependencies installed"
+#  else
+#    fail "error installing dependencies"
+#  fi
+#fi
 
 echo ''
 echo '  All installed!'
